# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: algohmp@gmail.com
author_name: knonode
cloud_provider: vercel
contract_name: mint_preset
preset_name: production
project_name: SOA

